# Generated by Django 4.1.7 on 2023-04-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='preco',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano_fabricacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano_modelo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='portas',
            field=models.IntegerField(),
        ),
    ]
