# Generated by Django 4.1.7 on 2023-04-02 00:05

import concessionaria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionaria', '0003_alter_veiculo_ano_fabricacao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loja',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='compra_cliente',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='compra_veiculo',
        ),
        migrations.AddField(
            model_name='compra',
            name='cpf',
            field=models.CharField(default=0, max_length=11, verbose_name=concessionaria.models.Cliente),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='nome',
            field=models.CharField(default=0, max_length=150, verbose_name=concessionaria.models.Cliente),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Veiculo',
        ),
    ]
