# Generated by Django 4.1.7 on 2023-04-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionaria', '0004_delete_loja_remove_compra_compra_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('ano_fabricacao', models.IntegerField()),
                ('ano_modelo', models.IntegerField()),
                ('tipo_veiculo', models.CharField(max_length=20)),
                ('portas', models.IntegerField()),
                ('motor', models.CharField(max_length=80)),
                ('potencia', models.CharField(max_length=10)),
                ('torque', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
