# Generated by Django 4.1.7 on 2023-04-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano_fabricacao', models.IntegerField(max_length=4)),
                ('ano_modelo', models.IntegerField(max_length=4)),
                ('tipo_veiculo', models.CharField(max_length=20)),
                ('portas', models.IntegerField(max_length=2)),
                ('motor', models.CharField(max_length=80)),
                ('potencia', models.CharField(max_length=10)),
                ('torque', models.CharField(max_length=10)),
            ],
        ),
    ]
