# Generated by Django 4.1.7 on 2023-04-01 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concessionaria', '0002_veiculo_preco_alter_veiculo_ano_fabricacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='ano_fabricacao',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano_modelo',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='portas',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='preco',
            field=models.CharField(max_length=9),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='concessionaria.cliente')),
                ('compra_veiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='concessionaria.veiculo')),
            ],
        ),
    ]
